analytics: {}
color:
  brandColors:
    - '#D8D8B8'
    - '#501830'
    - '#688898'
    - '#903848'
    - '#000000'
  brandStrength: 0.3298455465119332
  lightness: 0.25
  rhythmicContrast: 0
  saturation: 0.1875
cta: {}
layout_spectrum: 0.3686323892325163
name: truedax
opengraph: {}
purpose: []
typography_spectrum: 0.35383
