name: truedax
favicon: null
layout_spectrum: 0.3686323892325163
typography_spectrum: 0.35383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3988af'
    - '#163645'
    - '#b6b4bf'
    - '#fcfce0'
  brandStrength: 0.3298455465119332
  lightness: 0.07177936099469662
  saturation: 0.6793794047553092
  rhythmicContrast: 0.09440303687006235
purpose: []
