name: truedax
favicon: null
layout_spectrum: 0.50035
typography_spectrum: 0.52008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85b3c2'
    - '#5e6872'
    - '#34343c'
    - '#000000'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
