name: truedax
favicon: null
layout_spectrum: 0.75053
typography_spectrum: 0.52008
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3eaf2'
    - '#98a9d4'
    - '#cfa4ae'
    - '#49393c'
    - '#816161'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
