analytics: {}
color:
  brandColors:
    - '#e3eaf2'
    - '#98a9d4'
    - '#cfa4ae'
    - '#49393c'
    - '#816161'
  brandStrength: 0.5
  lightness: 0.25
  rhythmicContrast: 0
  saturation: 0.1875
cta: {}
layout_spectrum: 0.296171
name: truedax
opengraph: {}
purpose: []
typography_spectrum: 0.64657
