purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.5
  lightness: 0.5
  brandColors:
    - '#000000'
    - '#DDFFFF'
    - '#A5CEE4'
    - '#3C454E'
    - '#7C9FBB'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: truedax
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.52008
layout_spectrum: 0.37366
